@startuml
'https://plantuml.com/sequence-diagram
autonumber

actor "Customer" as C

participant "ListQuest_UI" as UI
participant "ListQuest_Controller" as CTR
participant "QuestionnairesRepository" as QR
participant "Questionnaire" as Q
participant "EvalVisitorOurGrammar" as Eval

activate C

C -> UI : I want to list Questionnaires
activate UI
activate CTR

UI -> CTR : findOpenQuestionnaires();

CTR -> QR : List<Questionnaires> findOpenQuestionnaires();
activate QR
deactivate QR

CTR --> UI : List<Questionnaires>
deactivate CTR
UI --> C : List Questionnaires

C -> UI : Choose one
UI -> CTR: getQuestionnaireById(text);
activate CTR

CTR -> QR : getQuestionnaireById(text)
activate QR
deactivate QR

CTR -> Eval : quest
activate Eval
deactivate Eval
note right: Realiza interação para responder\n e validar respostas

CTR --> UI : quest

deactivate CTR

UI --> C : Apresent Questionnaire





C -> UI : Answer Questionnaire











UI --> C : Confirm Answers

C -> UI : Confirmation Sucess

UI -> CTR : confirmQuestionnaire(quest)
activate CTR

CTR -> Q : setState()
activate Q
Q -> Q : setState(1)
deactivate Q

deactivate CTR

UI --> C : Operation sucess
deactivate UI


deactivate CTR




@enduml