@startuml
'https://plantuml.com/sequence-diagram
autonumber

actor "Customer" as C

participant "ClientCheckOrdersUI" as UI
participant "Order_Controller" as CTR
participant "Order_Repository" as OR
participant "Order" as O

activate C

C -> UI : I want to Check Open Orders
activate UI



UI -> CTR : getClientOpenOrders();
activate CTR

CTR -> SystemUser : getSystemUser()
activate SystemUser
SystemUser --> CTR : user
deactivate SystemUser


CTR -> OR : findOpenOrders(user)
activate OR
OR -> CTR : List<OrderType>
deactivate OR


CTR --> UI : List<OrderType>
deactivate CTR
UI --> C : List Open Orders

UI --> C : Operation sucess
deactivate UI


deactivate CTR




@enduml