@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Sales Manager" as SM
participant "CreateQuestionnaireUI" as UI
participant "QuestionnaireController" as CTR
participant "FileWrite" as FW
participant "FileWriter" as FWR


activate SM

SM->UI : Request to Create New Questionaire
activate UI
SM<--UI : Ask about fileName, title, wmsg
deactivate UI
SM->UI : Write needed data
activate UI
UI->CTR : createFile(fileName, title, wmsg)
activate CTR
CTR -> FW : createFile(fileName, title, wmsg)
activate FW
FW -> FWR : newFile()
activate FWR
deactivate FWR
deactivate FW
deactivate CTR
loop for each question addition

SM<--UI : Ask Question text, type(option or \n obligatory) and answer type \n(multiple choice,  numeric or text)
deactivate UI

SM->UI : Insert necessary information
activate UI

UI-> CTR : addQuestion(text,type, atype, fileName);
activate CTR
CTR -> FW : addQuestion(text,type, atype, fileName);
activate FW
deactivate FW
deactivate CTR


loop opt = multiple_choice


SM<--UI : Ask for possible answer to Question
deactivate UI
SM->UI : Write the requested data
activate UI

UI -> CTR : addPossibleAnswer(answer, fileName);
activate CTR
CTR -> FW : addPossibleAnswer(answer, fileName);
activate FW
deactivate FW
deactivate CTR

end

end
SM<--UI : Informs questionnaire creation (sucess)
deactivate UI

@enduml